//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOPLANLAR
    {
        public int HPL_ID { get; set; }
        public Nullable<int> HFT_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
        public string SUB_ADS { get; set; }
        public Nullable<int> KUL_ID { get; set; }
        public string HPL_PTESI { get; set; }
        public string HPL_IPTESI { get; set; }
        public string HPL_SALI { get; set; }
        public string HPL_ISALI { get; set; }
        public string HPL_CARS { get; set; }
        public string HPL_ICARS { get; set; }
        public string HPL_PERS { get; set; }
        public string HPL_IPERS { get; set; }
        public string HPL_CUMA { get; set; }
        public string HPL_ICUMA { get; set; }
    }
}
