//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARA_TBL1
    {
        public int ARA_ID { get; set; }
        public Nullable<int> SUB_ID { get; set; }
        public Nullable<int> DML_ID { get; set; }
        public Nullable<int> DYR_ID { get; set; }
        public Nullable<int> ODV_ID { get; set; }
        public Nullable<int> HFT_ID { get; set; }
    
        public virtual SUBELER SUBELER { get; set; }
        public virtual DAMLACIKLAR DAMLACIKLAR { get; set; }
        public virtual DUYURULAR DUYURULAR { get; set; }
        public virtual HAFTALAR HAFTALAR { get; set; }
        public virtual ODEVLER ODEVLER { get; set; }
    }
}
