//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANSLAR
    {
        public BRANSLAR()
        {
            this.KULLANICILAR = new HashSet<KULLANICILAR>();
        }
    
        public int BRS_ID { get; set; }
        public string BRS_AD { get; set; }
        public Nullable<int> BRS_SIRA { get; set; }
    
        public virtual ICollection<KULLANICILAR> KULLANICILAR { get; set; }
    }
}
