//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEVAPLAR
    {
        public int CVP_ID { get; set; }
        public Nullable<int> SNV_ID { get; set; }
        public Nullable<int> DRS_ID { get; set; }
        public string CVP_KA { get; set; }
        public string CVP_KB { get; set; }
        public string CVP_KC { get; set; }
        public string CVP_KD { get; set; }
    
        public virtual SINAVLAR SINAVLAR { get; set; }
    }
}
