//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CINSIYET
    {
        public short CNS_ID { get; set; }
        public string CNS_AD { get; set; }
        public string CNS_DEGER { get; set; }
    }
}
