//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAVRANIS
    {
        public int DAV_ID { get; set; }
        public Nullable<int> KUL_ID { get; set; }
        public Nullable<int> HFT_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
        public Nullable<int> DAV_KULID { get; set; }
        public string DAV_AD { get; set; }
        public Nullable<short> DAV_NOT { get; set; }
        public Nullable<bool> DAV_OLUMLU { get; set; }
        public Nullable<System.DateTime> DAV_TAR { get; set; }
    }
}
