//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAVRANISLAR
    {
        public int DVR_ID { get; set; }
        public string DVR_AD { get; set; }
        public Nullable<int> SNF_ID { get; set; }
        public Nullable<bool> DVR_OLUMLU { get; set; }
        public Nullable<short> DVR_NOT { get; set; }
    }
}
