//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVAMSIZ
    {
        public int DVM_ID { get; set; }
        public Nullable<int> KUL_ID { get; set; }
        public Nullable<int> HFT_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
        public Nullable<System.DateTime> DVM_TAR { get; set; }
        public string DVM_AD { get; set; }
        public Nullable<decimal> DVM_GUN { get; set; }
        public string DVM_MAZERET { get; set; }
    }
}
