//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRSSNVSNC
    {
        public int DSN_ID { get; set; }
        public Nullable<int> SNV_ID { get; set; }
        public Nullable<int> KUL_ID { get; set; }
        public Nullable<int> DRS_ID { get; set; }
        public Nullable<short> DSN_SS { get; set; }
        public Nullable<short> DSN_DS { get; set; }
        public Nullable<short> DSN_YS { get; set; }
        public Nullable<decimal> DSN_NS { get; set; }
        public Nullable<decimal> DSN_ORTSUB { get; set; }
        public Nullable<decimal> DSN_ORTSNF { get; set; }
        public Nullable<decimal> DSN_ORTOKL { get; set; }
        public Nullable<decimal> DSN_ORTKRM { get; set; }
        public Nullable<decimal> DSN_BSRYZD { get; set; }
        public string DSN_BSRYRM { get; set; }
        public Nullable<short> DSN_BS { get; set; }
        public Nullable<decimal> DSN_PUAN { get; set; }
        public Nullable<short> DSN_SRASUB { get; set; }
        public Nullable<short> DSN_SRASNF { get; set; }
        public Nullable<short> DSN_SRAOKL { get; set; }
        public Nullable<short> DSN_SRAKRM { get; set; }
        public Nullable<short> DSN_TOPSUB { get; set; }
        public Nullable<short> DSN_TOPSNF { get; set; }
        public Nullable<short> DSN_TOPOKL { get; set; }
        public Nullable<short> DSN_TOPKRM { get; set; }
        public string DSN_CVPANH { get; set; }
        public string DSN_CVPKUL { get; set; }
        public string DSN_CVPAE { get; set; }
        public string DSN_KTPCK { get; set; }
        public Nullable<decimal> DSN_YGS1 { get; set; }
        public Nullable<decimal> DSN_YGS2 { get; set; }
        public Nullable<decimal> DSN_YGS3 { get; set; }
        public Nullable<decimal> DSN_YGS4 { get; set; }
        public Nullable<decimal> DSN_YGS5 { get; set; }
        public Nullable<decimal> DSN_YGS6 { get; set; }
        public Nullable<decimal> DSN_MF1 { get; set; }
        public Nullable<decimal> DSN_MF2 { get; set; }
        public Nullable<decimal> DSN_MF3 { get; set; }
        public Nullable<decimal> DSN_MF4 { get; set; }
        public Nullable<decimal> DSN_TM1 { get; set; }
        public Nullable<decimal> DSN_TM2 { get; set; }
        public Nullable<decimal> DSN_TM3 { get; set; }
        public Nullable<decimal> DSN_TS1 { get; set; }
        public Nullable<decimal> DSN_TS2 { get; set; }
        public Nullable<decimal> DSN_DIL1 { get; set; }
        public Nullable<decimal> DSN_DIL2 { get; set; }
    
        public virtual SINAVLAR SINAVLAR { get; set; }
        public virtual KULLANICILAR KULLANICILAR { get; set; }
        public virtual DERSLER DERSLER { get; set; }
    }
}
