//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EOBSEntities : DbContext
    {
        public EOBSEntities()
            : base("name=EOBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KARNELER> KARNELER { get; set; }
        public DbSet<KULLANICILAR> KULLANICILAR { get; set; }
        public DbSet<KURLAR> KURLAR { get; set; }
        public DbSet<MESAJLAR> MESAJLAR { get; set; }
        public DbSet<SINIFLAR> SINIFLAR { get; set; }
        public DbSet<SUBELER> SUBELER { get; set; }
        public DbSet<YETKILER> YETKILER { get; set; }
        public DbSet<BRANSLAR> BRANSLAR { get; set; }
        public DbSet<CINSIYET> CINSIYET { get; set; }
        public DbSet<HAFTALAR> HAFTALAR { get; set; }
        public DbSet<ARA_TBL1> ARA_TBL1 { get; set; }
        public DbSet<DAMLACIKLAR> DAMLACIKLAR { get; set; }
        public DbSet<DUYURULAR> DUYURULAR { get; set; }
        public DbSet<ODEVLER> ODEVLER { get; set; }
        public DbSet<OZELNOTLAR> OZELNOTLAR { get; set; }
        public DbSet<ODEVSNCLAR> ODEVSNCLAR { get; set; }
        public DbSet<OZELNOT> OZELNOT { get; set; }
        public DbSet<ODEVSNC> ODEVSNC { get; set; }
        public DbSet<SINAVTIP> SINAVTIP { get; set; }
        public DbSet<CEVAPLAR> CEVAPLAR { get; set; }
        public DbSet<DRSSNVSNC> DRSSNVSNC { get; set; }
        public DbSet<SINAVLAR> SINAVLAR { get; set; }
        public DbSet<ARA_TBL2> ARA_TBL2 { get; set; }
        public DbSet<SINAVSNC> SINAVSNC { get; set; }
        public DbSet<RDSDERSLER> RDSDERSLER { get; set; }
        public DbSet<RDSLISTE> RDSLISTE { get; set; }
        public DbSet<KARNEDERS> KARNEDERS { get; set; }
        public DbSet<KARNEDERSNOT> KARNEDERSNOT { get; set; }
        public DbSet<OKULTUR> OKULTUR { get; set; }
        public DbSet<DEGEREGITIM> DEGEREGITIM { get; set; }
        public DbSet<AOPLANLAR> AOPLANLAR { get; set; }
        public DbSet<DERSLER> DERSLER { get; set; }
        public DbSet<OPTIK> OPTIK { get; set; }
        public DbSet<SINAVDETAY> SINAVDETAY { get; set; }
        public DbSet<RESIMLER> RESIMLER { get; set; }
        public DbSet<OKULLAR> OKULLAR { get; set; }
        public DbSet<HATALAR> HATALAR { get; set; }
        public DbSet<HEPTABLO> HEPTABLO { get; set; }
        public DbSet<SORUANALIZ> SORUANALIZ { get; set; }
        public DbSet<DAVRANISLAR> DAVRANISLAR { get; set; }
        public DbSet<DAVRANIS> DAVRANIS { get; set; }
        public DbSet<DEVAMSIZ> DEVAMSIZ { get; set; }
        public DbSet<SAYFALAR> SAYFALAR { get; set; }
    }
}
