//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HATALAR
    {
        public int ERR_ID { get; set; }
        public string ERR_MSG1 { get; set; }
        public string ERR_MSG2 { get; set; }
        public string ERR_MSG3 { get; set; }
        public string ERR_MSG4 { get; set; }
        public string ERR_MSG5 { get; set; }
        public string ERR_KUL { get; set; }
        public Nullable<System.DateTime> ERR_TAR { get; set; }
        public string ERR_KULMSG { get; set; }
    }
}
