//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEPTABLO
    {
        public int HEP_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
        public Nullable<short> HEP_GRUP { get; set; }
        public Nullable<int> KUL_ID { get; set; }
        public Nullable<short> HEP_H1 { get; set; }
        public Nullable<short> HEP_G1 { get; set; }
        public Nullable<short> HEP_H2 { get; set; }
        public Nullable<short> HEP_G2 { get; set; }
        public Nullable<short> HEP_H3 { get; set; }
        public Nullable<short> HEP_G3 { get; set; }
        public Nullable<short> HEP_H4 { get; set; }
        public Nullable<short> HEP_G4 { get; set; }
        public Nullable<short> HEP_H5 { get; set; }
        public Nullable<short> HEP_G5 { get; set; }
        public Nullable<short> HEP_H6 { get; set; }
        public Nullable<short> HEP_G6 { get; set; }
        public Nullable<short> HEP_H7 { get; set; }
        public Nullable<short> HEP_G7 { get; set; }
        public Nullable<short> HEP_H8 { get; set; }
        public Nullable<short> HEP_G8 { get; set; }
        public Nullable<short> HEP_H9 { get; set; }
        public Nullable<short> HEP_G9 { get; set; }
    
        public virtual KULLANICILAR KULLANICILAR { get; set; }
    }
}
