//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARNEDERSNOT
    {
        public int KDN_ID { get; set; }
        public Nullable<int> DRS_ID { get; set; }
        public Nullable<int> KUL_ID { get; set; }
        public bool KDN_MUAF { get; set; }
        public Nullable<short> KDN_DONEM { get; set; }
        public Nullable<short> KDN_S1 { get; set; }
        public Nullable<short> KDN_S2 { get; set; }
        public Nullable<short> KDN_S3 { get; set; }
        public Nullable<short> KDN_S4 { get; set; }
        public Nullable<short> KDN_PRO1 { get; set; }
        public Nullable<short> KDN_PRO2 { get; set; }
        public Nullable<decimal> KDN_PROORT { get; set; }
        public Nullable<short> KDN_PEK1 { get; set; }
        public Nullable<short> KDN_PEK2 { get; set; }
        public Nullable<short> KDN_PEK3 { get; set; }
        public Nullable<decimal> KDN_PEKORT { get; set; }
        public Nullable<short> KDN_PG1 { get; set; }
        public Nullable<short> KDN_PG2 { get; set; }
        public Nullable<short> KDN_PG3 { get; set; }
        public Nullable<short> KDN_PG4 { get; set; }
        public Nullable<short> KDN_PG5 { get; set; }
        public Nullable<decimal> KDN_PGORT { get; set; }
        public Nullable<decimal> KDN_PERORT { get; set; }
        public Nullable<short> KDN_NOT { get; set; }
        public Nullable<decimal> KDN_PUAN { get; set; }
    
        public virtual KULLANICILAR KULLANICILAR { get; set; }
        public virtual DERSLER DERSLER { get; set; }
    }
}
