//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARNEDERS
    {
        public int KDL_ID { get; set; }
        public Nullable<int> SNF_ID { get; set; }
        public Nullable<int> DRS_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
    
        public virtual SINIFLAR SINIFLAR { get; set; }
        public virtual DERSLER DERSLER { get; set; }
    }
}
