//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESAJLAR
    {
        public int MSJ_ID { get; set; }
        public string MSJ_METNI { get; set; }
        public string MSJ_KONU { get; set; }
        public Nullable<int> MSJ_KIM_ID { get; set; }
        public string MSJ_KIM { get; set; }
        public Nullable<int> MSJ_KIME_ID { get; set; }
        public string MSJ_KIME { get; set; }
        public Nullable<bool> MSJ_OKUNDU { get; set; }
        public Nullable<System.DateTime> MSJ_TAR { get; set; }
    
        public virtual KULLANICILAR GONDERENKUL { get; set; }
        public virtual KULLANICILAR ALANKUL { get; set; }
    }
}
