//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODEVSNC
    {
        public int ODE_ID { get; set; }
        public string ODE_NOT { get; set; }
        public Nullable<int> HFT_ID { get; set; }
        public Nullable<int> KUL_ID { get; set; }
        public Nullable<int> SNC_ID { get; set; }
        public bool ODE_AKTIF { get; set; }
        public string ODE_GRUP { get; set; }
        public bool ODE_DURUM1 { get; set; }
        public bool ODE_DURUM2 { get; set; }
        public bool ODE_DURUM3 { get; set; }
        public bool ODE_DURUM4 { get; set; }
        public bool ODE_DURUM5 { get; set; }
        public string ODE_SNC { get; set; }
        public Nullable<System.DateTime> ODE_TAR { get; set; }
    
        public virtual KULLANICILAR KULLANICILAR { get; set; }
        public virtual ODEVSNCLAR ODEVSNCLAR { get; set; }
    }
}
