//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODEVSNCLAR
    {
        public ODEVSNCLAR()
        {
            this.ODEVSNC = new HashSet<ODEVSNC>();
        }
    
        public int SNC_ID { get; set; }
        public string SNC_AD { get; set; }
        public string SNC_METIN { get; set; }
        public Nullable<int> HFT_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
        public string SUB_ADS { get; set; }
        public Nullable<int> KUL_ID { get; set; }
    
        public virtual ICollection<ODEVSNC> ODEVSNC { get; set; }
    }
}
