//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OKULLAR
    {
        public OKULLAR()
        {
            this.ARA_TBL2 = new HashSet<ARA_TBL2>();
            this.KULLANICILAR = new HashSet<KULLANICILAR>();
            this.KURLAR = new HashSet<KURLAR>();
            this.SINIFLAR = new HashSet<SINIFLAR>();
            this.SUBELER = new HashSet<SUBELER>();
        }
    
        public int OKL_ID { get; set; }
        public string OTR_KOD { get; set; }
        public string OKL_KODU { get; set; }
        public string OKL_ADI { get; set; }
        public string OKL_KISA { get; set; }
        public Nullable<int> OKL_SIRA { get; set; }
        public Nullable<int> RSM_ID { get; set; }
        public string OKL_SMSKULAD { get; set; }
        public string OKL_SMSSIFRE { get; set; }
        public string OKL_RESELLERID { get; set; }
        public string OKL_SMSBASLIK { get; set; }
    
        public virtual ICollection<ARA_TBL2> ARA_TBL2 { get; set; }
        public virtual ICollection<KULLANICILAR> KULLANICILAR { get; set; }
        public virtual ICollection<KURLAR> KURLAR { get; set; }
        public virtual RESIMLER RESIMLER { get; set; }
        public virtual ICollection<SINIFLAR> SINIFLAR { get; set; }
        public virtual ICollection<SUBELER> SUBELER { get; set; }
    }
}
