//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTIK
    {
        public OPTIK()
        {
            this.SINAVDETAY = new HashSet<SINAVDETAY>();
        }
    
        public int OPT_ID { get; set; }
        public string OPT_AD { get; set; }
        public Nullable<int> SDT_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
        public Nullable<short> OPT_OK_BAS { get; set; }
        public Nullable<short> OPT_OK_UZN { get; set; }
        public Nullable<short> OPT_TC_BAS { get; set; }
        public Nullable<short> OPT_TC_UZN { get; set; }
        public Nullable<short> OPT_NO_BAS { get; set; }
        public Nullable<short> OPT_NO_UZN { get; set; }
        public Nullable<short> OPT_KT_BAS { get; set; }
        public Nullable<short> OPT_D0_BAS { get; set; }
        public Nullable<short> OPT_D1_BAS { get; set; }
        public Nullable<short> OPT_D2_BAS { get; set; }
        public Nullable<short> OPT_D3_BAS { get; set; }
        public Nullable<short> OPT_D4_BAS { get; set; }
        public Nullable<short> OPT_D5_BAS { get; set; }
        public Nullable<short> OPT_D6_BAS { get; set; }
        public Nullable<short> OPT_D7_BAS { get; set; }
        public Nullable<short> OPT_D8_BAS { get; set; }
        public Nullable<short> OPT_D9_BAS { get; set; }
        public Nullable<short> OPT_D10_BAS { get; set; }
        public Nullable<short> OPT_D11_BAS { get; set; }
        public Nullable<short> OPT_D12_BAS { get; set; }
        public Nullable<short> OPT_D13_BAS { get; set; }
        public Nullable<short> OPT_D14_BAS { get; set; }
        public Nullable<short> OPT_AD_BAS { get; set; }
        public Nullable<short> OPT_AD_UZN { get; set; }
        public Nullable<short> OPT_SOY_BAS { get; set; }
        public Nullable<short> OPT_SOY_UZN { get; set; }
    
        public virtual ICollection<SINAVDETAY> SINAVDETAY { get; set; }
    }
}
