//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OZELNOT
    {
        public int OZN_ID { get; set; }
        public string OZN_NOT { get; set; }
        public Nullable<int> KUL_ID { get; set; }
        public Nullable<int> OZL_ID { get; set; }
        public bool OZN_AKTIF { get; set; }
        public string OZN_GRUP { get; set; }
        public Nullable<int> HFT_ID { get; set; }
        public Nullable<System.DateTime> OZN_TAR { get; set; }
    
        public virtual KULLANICILAR KULLANICILAR { get; set; }
        public virtual OZELNOTLAR OZELNOTLAR { get; set; }
    }
}
