//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDSLISTE
    {
        public int RDL_ID { get; set; }
        public Nullable<int> RDS_ID { get; set; }
        public Nullable<int> KUL_ID { get; set; }
    
        public virtual KULLANICILAR KULLANICILAR { get; set; }
        public virtual RDSDERSLER RDSDERSLER { get; set; }
    }
}
