//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESIMLER
    {
        public RESIMLER()
        {
            this.OKULLAR = new HashSet<OKULLAR>();
        }
    
        public int RSM_ID { get; set; }
        public string RSM_AD { get; set; }
        public string RSM_YOL { get; set; }
        public byte[] RSM_IMG { get; set; }
        public Nullable<int> OKL_ID { get; set; }
        public string RSM_DAD { get; set; }
        public string RSM_TYPE { get; set; }
    
        public virtual ICollection<OKULLAR> OKULLAR { get; set; }
    }
}
