//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAYFALAR
    {
        public int SYF_ID { get; set; }
        public string SYF_AD { get; set; }
        public Nullable<bool> SYF_ADMIN { get; set; }
        public Nullable<bool> SYF_OGRETMEN { get; set; }
        public Nullable<bool> SYF_OGRENCI { get; set; }
        public Nullable<bool> SYF_VELI { get; set; }
        public Nullable<bool> SYF_MISAFIR { get; set; }
    }
}
