//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINAVSNC
    {
        public int SNS_ID { get; set; }
        public Nullable<int> SNV_ID { get; set; }
        public Nullable<int> KUL_ID { get; set; }
        public Nullable<short> SNS_SS { get; set; }
        public Nullable<short> SNS_DS { get; set; }
        public Nullable<short> SNS_YS { get; set; }
        public Nullable<short> SNS_BS { get; set; }
        public Nullable<decimal> SNS_NS { get; set; }
        public Nullable<decimal> SNS_PUAN { get; set; }
        public Nullable<decimal> SNS_ORTSUB { get; set; }
        public Nullable<short> SNS_SRASUB { get; set; }
        public Nullable<short> SNS_TOPSUB { get; set; }
        public Nullable<decimal> SNS_ORTSNF { get; set; }
        public Nullable<short> SNS_SRASNF { get; set; }
        public Nullable<short> SNS_TOPSNF { get; set; }
        public Nullable<decimal> SNS_ORTOKL { get; set; }
        public Nullable<short> SNS_SRAOKL { get; set; }
        public Nullable<short> SNS_TOPOKL { get; set; }
        public Nullable<decimal> SNS_ORTKRM { get; set; }
        public Nullable<short> SNS_SRAKRM { get; set; }
        public Nullable<short> SNS_TOPKRM { get; set; }
        public Nullable<decimal> SNS_BSRYZD { get; set; }
        public string SNS_BSRYRM { get; set; }
        public string SNS_KTPCK { get; set; }
        public Nullable<decimal> SNS_YGS1 { get; set; }
        public Nullable<decimal> SNS_YGS2 { get; set; }
        public Nullable<decimal> SNS_YGS3 { get; set; }
        public Nullable<decimal> SNS_YGS4 { get; set; }
        public Nullable<decimal> SNS_YGS5 { get; set; }
        public Nullable<decimal> SNS_YGS6 { get; set; }
        public Nullable<decimal> SNS_MF1 { get; set; }
        public Nullable<decimal> SNS_MF2 { get; set; }
        public Nullable<decimal> SNS_MF3 { get; set; }
        public Nullable<decimal> SNS_MF4 { get; set; }
        public Nullable<decimal> SNS_TM1 { get; set; }
        public Nullable<decimal> SNS_TM2 { get; set; }
        public Nullable<decimal> SNS_TM3 { get; set; }
        public Nullable<decimal> SNS_TS1 { get; set; }
        public Nullable<decimal> SNS_TS2 { get; set; }
        public Nullable<decimal> SNS_DIL1 { get; set; }
        public Nullable<decimal> SNS_DIL2 { get; set; }
    
        public virtual KULLANICILAR KULLANICILAR { get; set; }
        public virtual SINAVLAR SINAVLAR { get; set; }
    }
}
