//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINAVDETAY
    {
        public SINAVDETAY()
        {
            this.SINAVLAR = new HashSet<SINAVLAR>();
        }
    
        public int SDT_ID { get; set; }
        public Nullable<short> STP_ID { get; set; }
        public string SDT_AD { get; set; }
        public string SDT_NOT { get; set; }
        public Nullable<short> SDT_TOPSORU { get; set; }
        public Nullable<decimal> SDT_TABPUAN { get; set; }
        public string SDT_DERSLER { get; set; }
        public Nullable<int> OPT_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
        public Nullable<int> SDT_DRS0 { get; set; }
        public Nullable<short> SDT_DRS0SS { get; set; }
        public Nullable<decimal> SDT_DRS0KS { get; set; }
        public Nullable<int> SDT_DRS1 { get; set; }
        public Nullable<short> SDT_DRS1SS { get; set; }
        public Nullable<decimal> SDT_DRS1KS { get; set; }
        public Nullable<int> SDT_DRS2 { get; set; }
        public Nullable<short> SDT_DRS2SS { get; set; }
        public Nullable<decimal> SDT_DRS2KS { get; set; }
        public Nullable<int> SDT_DRS3 { get; set; }
        public Nullable<short> SDT_DRS3SS { get; set; }
        public Nullable<decimal> SDT_DRS3KS { get; set; }
        public Nullable<int> SDT_DRS4 { get; set; }
        public Nullable<short> SDT_DRS4SS { get; set; }
        public Nullable<decimal> SDT_DRS4KS { get; set; }
        public Nullable<int> SDT_DRS5 { get; set; }
        public Nullable<short> SDT_DRS5SS { get; set; }
        public Nullable<decimal> SDT_DRS5KS { get; set; }
        public Nullable<int> SDT_DRS6 { get; set; }
        public Nullable<short> SDT_DRS6SS { get; set; }
        public Nullable<decimal> SDT_DRS6KS { get; set; }
        public Nullable<int> SDT_DRS7 { get; set; }
        public Nullable<short> SDT_DRS7SS { get; set; }
        public Nullable<decimal> SDT_DRS7KS { get; set; }
        public Nullable<int> SDT_DRS8 { get; set; }
        public Nullable<short> SDT_DRS8SS { get; set; }
        public Nullable<decimal> SDT_DRS8KS { get; set; }
        public Nullable<int> SDT_DRS9 { get; set; }
        public Nullable<short> SDT_DRS9SS { get; set; }
        public Nullable<decimal> SDT_DRS9KS { get; set; }
        public Nullable<int> SDT_DRS10 { get; set; }
        public Nullable<short> SDT_DRS10SS { get; set; }
        public Nullable<decimal> SDT_DRS10KS { get; set; }
        public Nullable<int> SDT_DRS11 { get; set; }
        public Nullable<short> SDT_DRS11SS { get; set; }
        public Nullable<decimal> SDT_DRS11KS { get; set; }
        public Nullable<int> SDT_DRS12 { get; set; }
        public Nullable<short> SDT_DRS12SS { get; set; }
        public Nullable<decimal> SDT_DRS12KS { get; set; }
        public Nullable<int> SDT_DRS13 { get; set; }
        public Nullable<short> SDT_DRS13SS { get; set; }
        public Nullable<decimal> SDT_DRS13KS { get; set; }
        public Nullable<int> SDT_DRS14 { get; set; }
        public Nullable<short> SDT_DRS14SS { get; set; }
        public Nullable<decimal> SDT_DRS14KS { get; set; }
    
        public virtual DERSLER DERSLER { get; set; }
        public virtual DERSLER DERSLER1 { get; set; }
        public virtual DERSLER DERSLER2 { get; set; }
        public virtual DERSLER DERSLER3 { get; set; }
        public virtual DERSLER DERSLER4 { get; set; }
        public virtual DERSLER DERSLER5 { get; set; }
        public virtual DERSLER DERSLER6 { get; set; }
        public virtual DERSLER DERSLER7 { get; set; }
        public virtual DERSLER DERSLER8 { get; set; }
        public virtual DERSLER DERSLER9 { get; set; }
        public virtual DERSLER DERSLER10 { get; set; }
        public virtual DERSLER DERSLER11 { get; set; }
        public virtual DERSLER DERSLER12 { get; set; }
        public virtual DERSLER DERSLER13 { get; set; }
        public virtual DERSLER DERSLER14 { get; set; }
        public virtual OPTIK OPTIK { get; set; }
        public virtual SINAVTIP SINAVTIP { get; set; }
        public virtual ICollection<SINAVLAR> SINAVLAR { get; set; }
    }
}
