//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINAVLAR
    {
        public SINAVLAR()
        {
            this.CEVAPLAR = new HashSet<CEVAPLAR>();
            this.DRSSNVSNC = new HashSet<DRSSNVSNC>();
            this.SINAVSNC = new HashSet<SINAVSNC>();
            this.SORUANALIZ = new HashSet<SORUANALIZ>();
        }
    
        public int SNV_ID { get; set; }
        public string SNV_AD { get; set; }
        public Nullable<int> SDT_ID { get; set; }
        public Nullable<int> SNF_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
        public bool SNV_KB { get; set; }
        public bool SNV_KC { get; set; }
        public bool SNV_KD { get; set; }
        public Nullable<short> SNV_KACY1D { get; set; }
        public bool SNV_DEG { get; set; }
        public Nullable<System.DateTime> SNV_DEGTAR { get; set; }
        public Nullable<System.DateTime> SNV_EKLTAR { get; set; }
        public Nullable<int> HFT_ID { get; set; }
        public Nullable<bool> SNV_KARNE { get; set; }
    
        public virtual ICollection<CEVAPLAR> CEVAPLAR { get; set; }
        public virtual ICollection<DRSSNVSNC> DRSSNVSNC { get; set; }
        public virtual ICollection<SINAVSNC> SINAVSNC { get; set; }
        public virtual SINAVDETAY SINAVDETAY { get; set; }
        public virtual HAFTALAR HAFTALAR { get; set; }
        public virtual ICollection<SORUANALIZ> SORUANALIZ { get; set; }
    }
}
