//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINAVTIP
    {
        public SINAVTIP()
        {
            this.SINAVDETAY = new HashSet<SINAVDETAY>();
        }
    
        public short STP_ID { get; set; }
        public string STP_AD { get; set; }
    
        public virtual ICollection<SINAVDETAY> SINAVDETAY { get; set; }
    }
}
