//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINIFLAR
    {
        public SINIFLAR()
        {
            this.KURLAR = new HashSet<KURLAR>();
            this.SUBELER = new HashSet<SUBELER>();
            this.RDSDERSLER = new HashSet<RDSDERSLER>();
            this.KARNEDERS = new HashSet<KARNEDERS>();
        }
    
        public int SNF_ID { get; set; }
        public string SNF_AD { get; set; }
        public Nullable<int> SNF_SIRA { get; set; }
        public Nullable<int> KRN_ID { get; set; }
        public Nullable<int> OKL_ID { get; set; }
    
        public virtual KARNELER KARNELER { get; set; }
        public virtual ICollection<KURLAR> KURLAR { get; set; }
        public virtual ICollection<SUBELER> SUBELER { get; set; }
        public virtual ICollection<RDSDERSLER> RDSDERSLER { get; set; }
        public virtual ICollection<KARNEDERS> KARNEDERS { get; set; }
        public virtual OKULLAR OKULLAR { get; set; }
    }
}
