//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOBSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YETKILER
    {
        public YETKILER()
        {
            this.KULLANICILAR = new HashSet<KULLANICILAR>();
        }
    
        public short YTK_ID { get; set; }
        public string YTK_AD { get; set; }
        public Nullable<short> YTK_KODU { get; set; }
    
        public virtual ICollection<KULLANICILAR> KULLANICILAR { get; set; }
    }
}
